<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

return new class extends Migration
{
    /**
     * Run the migrations.
     */

    public function up(): void
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('key')->unique();
            $table->string('value')->nullable();
            $table->string('display_name')->nullable();
            $table->string('description')->nullable();
            $table->string('category')->nullable();
            $table->string('type')->nullable();
            $table->string('options')->nullable();
            $table->string('placeholder')->nullable();
            $table->string('default')->nullable();
            $table->string('required')->nullable();
            $table->string('order')->nullable();
            $table->string('html_attributes')->nullable();
            $table->timestamps();
        });

        // Add built-in settings
        $settings = [
            [
                'id' => Str::uuid()->toString(),
                'key' => 'site_name',
                'value' => 'Kostüm Kuru Temizleme',
                'display_name' => 'Site Adı',
                'description' => 'Site adınızı buradan değiştirebilirsiniz. Sitenizin adının gözüktüğü her yerde değişiklik sağlanır.',
                'category' => 'general',
                'type' => 'text',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 1,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'site_owner',
                'value' => 'İbrahim Gönül',
                'display_name' => 'Site Sahibi (İsim - Soyisim)',
                'type' => 'text',
                'description' => 'Site sahibinin ismini değiştirebilirsiniz. Bu bilginin gösterildiği herhangi bir yer yok ancak Google gibi arama motorları bu bilgiyi kullanabilir.',
                'category' => 'general',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 2,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'shop_location',
                'value' => 'Beşiktaş/İstanbul',
                'display_name' => 'Mağaza Adresi',
                'type' => 'text',
                'description' => 'Mağazanızın adresini buradan değiştirebilirsiniz. Bu adresiniz anasayfa da görünen Google Maps görüntüsü ve bilgi için kullanılacaktır.',
                'category' => 'general',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 3,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'working_hours_start',
                'value' => '08:30',
                'display_name' => 'Çalışma Saatleri Başlangıcı',
                'type' => 'time',
                'description' => 'Mağazanın çalışma saati başlangıcı ayarlayın. Bu ayar ile birlikte çalışma saatleri dışında randevu alınamaz, site de şubenin kapalı olduğu belirtilir.',
                'category' => 'general',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 4,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'working_hours_end',
                'value' => '19:00',
                'display_name' => 'Çalışma Saatleri Bitişi',
                'type' => 'time',
                'description' => 'Mağazanın çalışma saati bitişini ayarlayın. Bu ayar ile birlikte çalışma saatleri dışında randevu alınamaz, site de şubenin kapalı olduğu belirtilir.',
                'category' => 'general',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 5,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'working_days',
                'value' => '1,2,3,4,5,6',
                'display_name' => 'Çalışma Günleri',
                'type' => 'select',
                'description' => 'Mağazanızın çalışma günlerini ayarlayın. Bu ayar ile birlikte çalışma günleri dışında randevu alınamaz, site de şubenin kapalı olduğu belirtilir.',
                'category' => 'general',
                'options' => "['1', '2', '3', '4', '5', '6', '7']",
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 6,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'sms_number',
                'value' => '0212 260 60 63',
                'display_name' => 'İletişim No',
                'type' => 'tel',
                'html_attributes' => "pattern='[0-9]{4} [0-9]{3} [0-9]{2} [0-9]{2}'",
                'placeholder' => '0212 260 60 63',
                'description' => 'Bu numara ile müşterileriniz sizinle iletişime geçebilir. Ayrıca müşterilerinize bilgilendirme Whatsapp mesajları bu numara üzerinden gönderilir. 0212 260 60 63',
                'category' => 'general',
                'options' => null,
                'default' => null,
                'required' => null,
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'email_address',
                'value' => 'iletisim@kostumkurutemizleme.com.tr',
                'display_name' => 'İletişim Email',
                'type' => 'email',
                'description' => 'İletişim email adresinizi buradan değiştirebilirsiniz. Bu email adresi ile müşterileriniz sizinle iletişime geçebilir. Ayrıca müşterilerinize bilgilendirme mailleri bu mail adresi üzerinden gönderilir.',
                'category' => 'general',
                'options' => null,
                'default' => null,
                'required' => null,
                'placeholder' => null,
                'order' => 8,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'key' => 'facebook_link',
                'value' => 'https://www.facebook.com/kostumkurutemizleme',
                'display_name' => 'Facebook Linki',
                'description' => 'Facebook linkini buradan değiştirebilirsiniz.',
                'type' => 'text',
                'placeholder' => 'https://www.facebook.com/',
                'category' => 'socials',
                'options' => null,
                'default' => null,
                'required' => null,
                'order' => 9,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(), 'key' => 'instagram_url', 
                'value' => 'https://www.instagram.com/',
                'display_name' => 'Instagram Linki',
                'description' => 'Instagram linkini buradan değiştirebilirsiniz.',
                'type' => 'text',
                'placeholder' => 'https://www.instagram.com/',
                'category' =>'socials',
                'options' => null,
                'default' => null,
                'required' => null,
                'order' => 10,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(), 'key' => 'twitter_url', 
                'value' => 'https://twitter.com/',
                'display_name' => 'Twitter Linki',
                'description' => 'Twitter linkini buradan değiştirebilirsiniz.',
                'type' => 'text',
                'placeholder' => 'https://twitter.com/',
                'category' =>'socials',
                'options' => null,
                'default' => null,
                'required' => null,
                'order' => 11,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(), 'key' => 'linkedin_url', 
                'value' => 'https://www.linkedin.com/',
                'display_name' => 'Linkedin Linki',
                'description' => 'Linkedin linkini buradan değiştirebilirsiniz.',
                'type' => 'text',
                'placeholder' => 'https://www.linkedin.com/',
                'category' =>'socials',
                'options' => null,
                'default' => null,
                'required' => null,
                'order' => 12,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(), 'key' => 'youtube_url', 
                'value' => 'https://www.youtube.com/',
                'display_name' => 'Youtube Linki',
                'description' => 'Youtube linkini buradan değiştirebilirsiniz.',
                'type' => 'text',
                'placeholder' => 'https://www.youtube.com/',
                'category' =>'socials',
                'options' => null,
                'default' => null,
                'required' => null,
                'order' => 13,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(), 'key' => 'google_maps_location_url', 
                'value' => 'https://www.google.com/maps/embed/v1/place?q=Türkali,+KOSTÜM+KURU+TEMİZLEME,+Nüzhetiye+Caddesi,+Beşiktaş/İstanbul,+Türkiye&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8&zoom=14',
                'display_name' => 'Google Maps Linki',
                'description' => 'Google maps linkini buradan değiştirebilirsiniz.',
                'type' => 'text',
                'placeholder' => 'https://www.google.com/maps/embed/v1/place?',
                'category' =>'socials',
                'options' => null,
                'default' => null,
                'required' => null,
                'order' => 14,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(), 'key' => 'show_product_price_on_appointments_page',
                'value' => 'false',
                'display_name' => 'Randevu Sayfasında Ürün Fiyatlarını Göster',
                'description' => 'Randevu sayfasında ürün fiyatlarını göstermek için bu ayarı aktif edin.',
                'type' => 'checkbox',
                'category' => 'general',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 15,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(), 'key' => 'smtp_mail_server', 
                'value' => null,
                'display_name' => 'SMTP Mail Sunucusu',
                'description' => 'Mail gönderilebilmesi için SMTP mail sunucusu ayarlarınızı buradan yapabilirsiniz.',
                'type' => 'text',
                'category' => 'custom',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 16,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(), 'key' => 'show_availability_on_home_page', 
                'value' => 'true',
                'display_name' => 'Müsaitlik Takvimini Anasayfada Göster',
                'description' => 'Müsaitlik takvimini anasayfada göstermek için bu ayarı aktif edin.',
                'type' => 'checkbox',
                'category' => 'general',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 17,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id'=> Str::uuid()->toString(),
                'key' => 'working_hours_headers',
                'value' => 'Pazartesi - Cumartesi / 08:00 - 19:30',
                'category' => 'general',
                'display_name' => 'Çalışma Saatleri Üst Bilgi',
                'description' => 'Çalışma saatlerinin gösterildiği sayfanın en üst bölümünde bulunan kısmı değiştirir.',
                'type' => 'text',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 18,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'working_hours_home',
                'value' => 'Pazar hariç her gün / 08:00 - 19:30',
                'category' => 'general',
                'display_name' => 'Çalışma Saatleri Anasayfa',
                'description' => 'Çalışma saatlerinin gösterildiği anasayfanın en altında çalışma saatlerimiz başlığının altındaki kısmı değiştirir.',
                'type' => 'text',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 19,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'shop_address',
                'value' => 'Türkali, Nüzhetiye Caddesi, No 16/A Beşiktaş/İstanbul',
                'description' => 'Mağazanızın adresini buradan değiştirebilirsiniz. Bu adresiniz anasayfa da görünen Google Maps görüntüsü ve bilgi için kullanılacaktır.',
                'category' => 'general',
                'display_name' => 'Adres',
                'type' => 'text',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 20,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'enable_registration',
                'value' => 'true',
                'category' => 'general',
                'display_name' => 'Müşteri Kaydı',
                'description' => 'Müşterilerin kayıt olabilmesi için bu ayarı aktif edin.',
                'type' => 'checkbox',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 21,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'enable_appointments',
                'value' => 'true',
                'category' => 'general',
                'display_name' => 'Randevular',
                'description' => 'Randevuların oluşturulması için bu ayarı aktif edin.',
                'type' => 'checkbox',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 22,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'privacy_policy_content',
                'value' => null,
                'category' => 'custom',
                'display_name' => 'Gizlilik Politikası',
                'description' => 'Gizlilik politikasını buradan değiştirebilirsiniz.',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 23,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'terms_of_service_content',
                'value' => null,
                'category' => 'custom',
                'display_name' => 'Kullanım Şartları',
                'description' => 'Kullanım şartlarını buradan değiştirebilirsiniz.',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 24,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'enable_notifications',
                'value' => 'true',
                'category' => 'general',
                'display_name' => 'Bildirimler',
                'description' => 'Bildirimlerin gönderilmesi için bu ayarı aktif edin.',
                'type' => 'checkbox',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 25,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'enable_ratings',
                'value' => 'true',
                'category' => 'general',
                'display_name' => 'Yorumlar',
                'description' => 'Yorumların oluşturulması için bu ayarı aktif edin.',
                'type' => 'checkbox',               
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 26,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'notification_options',
                'value' => '{}',
                'category' => 'general',
                'display_name' => 'Bildirimler',
                'description' => 'Bildirimlerin gönderilmesi için bu ayarı aktif edin.',
                'type' => 'select',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 27,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'=> Str::uuid()->toString(),
                'key' => 'shop_open_close',
                'value' => '{}',
                'category' => 'general',
                'display_name' => 'Mağaza Durumu',
                'description' => 'Mağazayı açın veya kapatın. Bu değişiklik anasayfada gösterilir. Bu süreç normalde otomatik olarak gerçekleşir.',
                'type' => 'checkbox',
                'options' => null,
                'placeholder' => null,
                'default' => null,
                'required' => null,
                'order' => 0,
                'html_attributes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Add more settings here as needed
        ];

        DB::table('settings')->insert($settings);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('settings');
    }
};
